# Generated by Django 3.2.5 on 2021-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsklad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='mass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='prov',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='qual',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
